export enum SOCKET_EVENTS {
  CREATE_GAME = "CREATE_GAME",
  JOIN_GAME = "JOIN_GAME",
  GAME_UPDATE = "GAME_UPDATE",
  SELECT_PIECE = "SELECT_PIECE",
  PLACE_SELECTED_PIECE_IN_CELL = "PLACE_SELECTED_PIECE_IN_CELL",
}
